### ISSUE TITLE
Add support to Swift Package Manager

### ISSUE THREAD

**Issue by rafagan** [rive-app/rive-ios#111]
Considering that SPM is the official Dependency Manager support from Apple, shouldn't it have support for Rive iOS?

**Comment by rafagan** [comment]
Any progress?

**Comment by zplata** [comment]
Hi @rafagan, thanks for opening this. We're looking into this currently, and can post back when we've got something to consume!

**Comment by AirborneEagle** [comment]
+1 This is a large large road block to adoption of Rive.
Currently on a new app and was given the task to add Rive animations, but can't because of this.

**Comment by brianschardt** [comment]
+1 Using swiftUI and swift package manager, road block for us.

**Comment by AirborneEagle** [comment]
I have been trying to add as a submodule, but cannot get it working. 
the closest I have gotten was by cloning the project (as explained in the README) and then adding the RiveRuntime as a Build Phase dependency. 

but it fails with an error in `rive_render_view.mm` 

`'include/core/SkSurface.h' file not found` 

I have no ideas on where to go from here. 
Any thoughts? @zplata

**Comment by zplata** [comment]
Thanks for hanging in there while we sort out the SwiftUI and Swift Package Manager business --

We just merged support for the Swift Package Manager - so you should be able to search for the `rive-ios-pod`. We'll update docs shortly!

For SwiftUI support, we're still working on an experimental API right now that we'll look to solidify over the next few releases.

**Comment by AirborneEagle** [comment]
You all are amazing! ❤️ 
We will try it out as soon as possible!!

**Comment by AirborneEagle** [comment]
Oh Man! it is working! 🎉 

I have been able to show a rive animation from an http resource, but local resources are not yet loading.  
with
```
RiveViewSwift(resource: "test-message-icon")
```
It fails to locate the asset `test-message-icon.riv` 

So as far as SPM support, this ticket is closed! 😄 
but could you offer any guidance on using a local asset as resource?

**Comment by AirborneEagle** [comment]
okay. upon further testing and examination of the rive examples code, it looks like the rive files are being added directly as files, and not into the `Assets.xcassets`

So Yay! we can now use our rive animations in our app!
Thank you again for your "swift" work on SPM support. (pun intended 😛 )


@zplata  Do you know if there is a way to use rive animations stored under `Assets.xcassets`?
