### ISSUE TITLE
Adding to existing project

### ISSUE THREAD

**Issue by JaapWijnen** [rive-app/rive-ios#12]
Any plans for instructions on adding this to an existing iOS project? I'm curious what the preferred way of adding this to a project would be. I'm mostly using the swift package manager for my dependencies.

**Comment by mjohnsullivan** [comment]
The runtime is now up in CocoaPods; instructions for installing can be found on the [Github](https://github.com/rive-app/rive-ios) and [Help Center](https://help.rive.app/runtimes/quick-start) pages.
