### ISSUE TITLE
Set color of icon

### ISSUE THREAD

**Issue by derech1e** [rive-app/rive-ios#191]
Hey, is there currently a way to set the color of an icon in SwiftUI programmatically?

The idea is that the icon automatically obtains the color from the background color like seen below.

![Bildschirmfoto 2022-05-29 um 20 43 59](https://user-images.githubusercontent.com/39240736/170886630-4ed9ce8c-68cd-4649-b887-286e12a85abc.png)

So in the previous Image I solved this by using the blend mode in SwiftUI `
            .blendMode(selectedTab == tab.selection ? .overlay : .normal)`

But this don't quite work as you can see below.
![Bildschirmfoto 2022-05-29 um 20 46 11](https://user-images.githubusercontent.com/39240736/170886671-daa6e50b-0aed-4466-9c4f-9f02c6eb7267.png)

Is there any solution or already plans/thoughts to implement this?

Thank you for your great Software!

**Comment by zplata** [comment]
@derech1e - There isn't a great way to get into that granular level of dynamically changing fills on particular nodes yet - however, you might try creating different states for the icon in a state machine that has fills for the different cases in your project.
