### ISSUE TITLE
Cannot find 'RiveViewModel' in scope

### ISSUE THREAD

**Issue by XAmateur** [rive-app/rive-ios#192]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/4157878/171666726-076245d0-5fcc-4af1-9c46-8e54e502c5f2.png">

**Comment by duncandoit** [comment]
It looks like your RiveRuntime package needs updating. It's currently pointing to version 1.0.18 and should be either pointing to the 'main' branch or version 2.0.19
