### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by maxgribov** [rive-app/rive-ios#197]
I noticed that `RiveExample` does not clear the memory when you close the view with animations. 

<img width="1165" alt="Screenshot 2022-06-05 at 23 48 24" src="https://user-images.githubusercontent.com/6514571/172070117-0a7d95a3-1503-44c6-9491-dbc754875c68.png">

How to reproduce:
1. Launch the `RiveExample` application (on the simulator or on the device)
2. Open and close the `Touch Events!` screen several times

I also did a quick profiling on leaks and found a huge amount of them:

<img width="1396" alt="Screenshot 2022-06-05 at 23 45 52" src="https://user-images.githubusercontent.com/6514571/172070173-f3869ac2-6986-40b0-92f8-58ccc07ccdba.png">

It looks like leaks happen in `RiveRuntime` library.

**Comment by duncandoit** [comment]
fixed

**Comment by BrotskyS** [comment]
> fixed

How?

**Comment by duncandoit** [comment]
The memory leak was related to image handling in the cpp runtime. A fix was made there and that change was propagated out to iOS.
