### ISSUE TITLE
'river/File.hpp' file not found

### ISSUE THREAD

**Issue by lmcmz** [rive-app/rive-ios#211]
### Description

Got a build error in the example app.

### Provide a Repro

1. Download the repo
2. Open `Rive.xcworkspace` from Xcode
3. Run the example app in the simulator
4. Error occur

### Expected behavior
It should work fine with example app

#### Screenshots

![Screen Shot 2022-06-29 at 12 01 58 am](https://user-images.githubusercontent.com/9669733/176198616-33bf66f7-5dc6-42e3-9e93-cf4da5d3d228.png)

### Device & Versions (please complete the following information)
- Device: iOS Simulator
- iOS version iOS 15
- Xcode: 13.4.1 & 14 beta

**Comment by duncandoit** [comment]
When cloning the repo you must run a script to build Skia before the project will build. From the root project directory run this: `./scripts/configure.sh`

**Comment by OskarGroth** [comment]
This is still happening, and there is no `./scripts/configure.sh`.

**Comment by duncandoit** [comment]
@OskarGroth  The script to run has been renamed to `./scripts/build.sh all`
