### ISSUE TITLE
Animation progress

### ISSUE THREAD

**Issue by insaite** [rive-app/rive-ios#278]
Thank you for such a wonderful tool for working with animations.

I am displaying a metronome animation, and at a certain point in the animation playback, I need to trigger vibration. To do this, I need to know the current playback progress of the animation. Can someone please explain how to obtain the current progress? Thanks!

**Comment by HayesGordon** [comment]
Hi @insaite 

A potentially easier way to achieve this desired outcome is by using the new feature that just launched, Events:
https://www.youtube.com/watch?v=Yg8ObnyEhIk

It's a way for the animation to send information to the runtime at the precise point in time needed.

Runtime documentation: https://help.rive.app/runtimes/rive-events

**Comment by insaite** [comment]
onRiveEventReceived never called
