### ISSUE TITLE
Crash on setTextRunValue

### ISSUE THREAD

**Issue by Masataka-n** [rive-app/rive-ios#286]
### Description

The `setTextRunValue` now throws an error, but if you execute it with an incorrect textRunName, it doesn't throw an error, and a runtime error occurs.
Help appreciate, thanks!

<img width="1226" alt="image" src="https://github.com/rive-app/rive-ios/assets/14210434/3c4f6b9a-dd9d-4c90-add8-03cf6069c0c1">

### Device & Versions (please complete the following information)
- Device: iOS Simulator, iPhone 13 Pro Max
- iOS version: iOS 17.0, iOS 16.1.1
- SDK version: 5.6.2

**Comment by zplata** [comment]
Hi @Masataka-n - we should be throwing an error appropriately that the text run value couldn't be set if it cannot find the text run reference on the Artboard, so we'll take a look at our internal error catching there.

However, do you mind clarifying this part:
> if you execute it with an incorrect textRunName, it doesn't throw an error

We expect an incorrect text run name to yield the error, and the correct text run name to propagate the value accordingly. If this isn't the case for you and you find the opposite happening on your end, it'd be great if you're able to provide a sample xcode project here so we can see if we can replicate on our end!

**Comment by Masataka-n** [comment]
Hi, @zplata
This issue can be reproduced with the sample app provided in this repository. 

The following is a modification made to [SwiftTestText.swift](https://github.com/rive-app/rive-ios/blob/main/Example-iOS/Source/Examples/SwiftUI/SwiftTestText.swift). 
The RunName in `setTextRunValue` has been changed, and a do-catch block has been added.

When an incorrect RunName is specified, an error is not thrown; instead, it results in a RunTimeError.

Help appreciate, thanks!

https://github.com/rive-app/rive-ios/assets/14210434/cdb63095-4d72-433b-8ada-8cb5cfe8a014

**Comment by zplata** [comment]
Thanks @Masataka-n ! We've got a patch in the works. We'll update this thread when it lands in a release.

**Comment by zplata** [comment]
Hi @Masataka-n - this should be fixed in `v5.7.0`. Closing this but feel free to re-open if you're still encountering issues with the text runs
