### ISSUE TITLE
Missing Privacy Manifest

### ISSUE THREAD

**Issue by pkrll** [rive-app/rive-ios#295]
### Description

Uploading our app that includes the Rive SPM to App Store generates an issue:

`ITMS-91053: Missing API declaration - Your app’s code in the ... file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. 
`

I've been trying to track down this issue. I might be mistaken, but it looks like it is the Rive package that causes this issue, as I could find references to the method `stat` (which according to [Apple's documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393) would trigger this warning).

Are you aware of this?

**Comment by Kaspik** [comment]
I don't see a warning in our project and we use Rive on iOS too.

Note that it's not only `stat` but also other methods, even simple creation of object in Photos library.

<img width="635" alt="Screenshot 2024-03-25 at 16 27 43" src="https://github.com/rive-app/rive-ios/assets/7204168/a2323e08-6d0f-46de-9ff9-91d6aeef7043">

**Comment by pkrll** [comment]
Thank you, @Kaspik . I'll take an even closer look in our project, I probably missed something then.

**Comment by nicolasmarchal** [comment]
Using cocoapods and RiveRuntime 5.11.1, 
I also have warnings when publishing to App store
- NSPrivacyAccessedAPICategoryFileTimestamp for stat,fstat
- NSPrivacyAccessedAPICategorySystemBootTime for mach_absolute_time

**Comment by caudetgit** [comment]
Fyi, we are currently working on this.

**Comment by caudetgit** [comment]
https://github.com/rive-app/rive-ios/pull/313
