### ISSUE TITLE
Stop Other Music App

### ISSUE THREAD

**Issue by y-daniel-1113** [rive-app/rive-ios#301]
When the app goes into the background, other music apps stop working.

**Comment by y-daniel-1113** [comment]
The cause is probably

- (void)didEnterBackground:(NSNotification*)notification
{
    rive::AudioEngine::RuntimeEngine()->stop();
}

**Comment by AlexanderBZ** [comment]
Would love to get this fixed as well. Users are messaging our team and saying they won't use the app since our Rive animations are stopping their other music apps.

**Comment by molind** [comment]
We've rolled back rive to the previous release until this bug is fixed. It's a critical bug and I'm surprised it haven't received enough attention.

**Comment by AlexanderBZ** [comment]
Awesome, thank you!

**Comment by psbss** [comment]
Same. This is critical issue for our product. We rolled back to v5.10.0, so We couldn't use sound feature.
Please provide us the handler.

**Comment by dskuza** [comment]
`rive-ios` v5.15.1 and above will now by default mix audio rather than stop other audio sources from playing, so if you update to the latest runtime, you should see this behavior fixed.

**Comment by dskuza** [comment]
`rive-ios` v5.15.1 and above will now by default mix audio rather than stop other audio sources from playing, so if you update to the latest runtime, you should see this behavior fixed.

**Comment by molind** [comment]
It could be closed already as resolved.
