### ISSUE TITLE
[5.11.3] Release publishing

### ISSUE THREAD

**Issue by NikitaDudin** [rive-app/rive-ios#311]
Version 5.11.3 not exists in Cocoapods repo.

- 5.11.2 exists. 
https://github.com/CocoaPods/Specs/blob/master/Specs/8/2/2/RiveRuntime/5.11.2/RiveRuntime.podspec.json

**Comment by steflsd** [comment]
[!] CocoaPods could not find compatible versions for pod "RiveRuntime":
  In Podfile:
    rive-react-native (from `../node_modules/rive-react-native`) was resolved to 7.0.3, which depends on
      RiveRuntime (= 5.11.3)

None of your spec sources contain a spec satisfying the dependency: `RiveRuntime (= 5.11.3)`.
