### ISSUE TITLE
Getting issue Animation work fine in preview but not working on iOS code

### ISSUE THREAD

**Issue by Spatel91111** [rive-app/rive-ios#325]
I have one "riv" file and it's working fine on https://rive.app/preview/ but on iOS swift code it's not working

I have add code as below

import UIKit
import RiveRuntime

class ViewController: UIViewController {
    
    let riveModel = RiveViewModel(fileName: "loading_loop", autoPlay: true)
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        let riveView = self.riveModel.createRiveView()
        self.view.addSubview(riveView)
        riveView.frame = self.view.bounds
    }
}

For library
Install latest SPM

**Comment by dskuza** [comment]
@Spatel91111 Are you still experiencing this issue?
