### ISSUE TITLE
Solos Support

### ISSUE THREAD

**Issue by frsisalima** [rive-app/rive-ios#326]
How to use 'Solos' in SwiftUI to show/hide components, or if 'Solos' is not supported, how can I hide/show elements at runtime?

**Comment by HayesGordon** [comment]
Hey @frsisalima, Solos is an Editor feature and not a runtime feature. You can set a solo through the state machine, and set a state machine at runtime. See our docs on setting a state machine input: https://rive.app/community/doc/state-machines/docxeznG7iiK#controlling-state-machine-inputs

We have a video about the Solos feature here: https://www.youtube.com/watch?v=fRtsldzaHC8

We have a public [Feature Request](https://rive.app/community/forums/feature-requests/fsyCzA4A9Yar) if you feel like this should be a runtime feature for all of Rive's runtimes.

Closing this issue for now!
