### ISSUE TITLE
I cannot build the Example (iOS) project - error 'rive/file.hpp' file not found

### ISSUE THREAD

**Issue by ManjitBedi** [rive-app/rive-ios#331]
### Description

I have downloaded the example code from this repo & opened the Example (iOS) project in Xcode 15.4.

When I build the project the following error occurs:

'rive/file.hpp' file not found

<img width="726" alt="Screenshot 2024-07-16 at 1 44 22 PM" src="https://github.com/user-attachments/assets/9aa84fc9-7b5b-42d3-b826-887992e5cea5">

**Comment by ManjitBedi** [comment]
It seems I can specify the Preview target instead; I don't know why there are multiple projects & some work & some don't.

**Comment by cerupcat** [comment]
@ManjitBedi probably makes sense to re-open this given it is still an issue.

**Comment by tslater** [comment]
@ManjitBedi  @cerupcat  Did you find a way to fix this?

**Comment by aabantariqmurtaza** [comment]
@ManjitBedi  no solution yet?
