### ISSUE TITLE
Sound Plays from Device Speaker Instead of Headphones When Playing AudioAsset.

### ISSUE THREAD

**Issue by psbss** [rive-app/rive-ios#332]
### Description

When playing an AudioAsset, the sound comes out from the device’s speaker even though headphones are being used.

#### Source `.riv`/`.rev` file

sent email to hello_at_rive.app with title "Rive iOS Issue #332"

### Expected behavior

Sound plays from device speaker

### Device & Versions (please complete the following information)

- SDK v5.15.1
- iOS v17.5.1

**Comment by dskuza** [comment]
@psbss This should be fixed now - the latest v6.x release contains a fix. It also adds a _little_ more configurability by respecting `AVAudioSessin` settings. We created a new doc for [playing audio[(https://rive.app/community/doc/playing-audio/docuEtbvcWOm) with some iOS details.
