### ISSUE TITLE
Can't build Rive

### ISSUE THREAD

**Issue by ashidov-fy** [rive-app/rive-ios#335]
### Description
I’m trying to build Rive following the steps outlined in CONTRIBUTING.md. 
However, the build process fails with the following error:

```
./scripts/build.sh all
....
+ premake5 --config=debug --out=out/iphoneos_debug --arch=universal --scripts=/Users/ashamazshidov/Projects/rive/rive-ios/scripts/../submodules/rive-cpp/build --os=ios gmake2
+ make -C out/iphoneos_debug clean
+ make -C out/iphoneos_debug -j12 rive_cg_renderer
+ popd
+ cp -r /Users/ashamazshidov/Projects/rive/rive-ios/scripts/../submodules/rive-cpp/cg_renderer/out/iphoneos_debug/librive_cg_renderer.a /Users/ashamazshidov/Projects/rive/rive-ios/scripts/../dependencies/debug/librive_cg_renderer.a
+ cp -r /Users/ashamazshidov/Projects/rive/rive-ios/scripts/../submodules/rive-cpp/cg_renderer/include /Users/ashamazshidov/Projects/rive/rive-ios/scripts/../dependencies/includes/cg_renderer
+ pushd /Users/ashamazshidov/Projects/rive/rive-ios/scripts/../Source/Renderer/NullPLS
./scripts/build.sh: line 59: pushd: /Users/ashamazshidov/Projects/rive/rive-ios/scripts/../Source/Renderer/NullPLS: No such file or directory
```

[build.log.zip](https://github.com/user-attachments/files/16714301/build.log.zip)

### Provide a Repro
[e5079d16abd833bf48e098f51ad0f2ad632ce551](https://github.com/rive-app/rive-ios/commit/e5079d16abd833bf48e098f51ad0f2ad632ce551)

### Expected behavior
The build should complete successfully without any errors.

### Device & Versions
**MacOS** 14.6.1 (Apple M3 Max)
**ninja** 1.12.1
**premake5** 5.0.0-dev
**git-lfs** 3.5.1 (GitHub; darwin arm64; go 1.22.1)

**Comment by dskuza** [comment]
@ashidov-fy We're working on updating the docs; I'll should have a status update in the coming days.

**Comment by dskuza** [comment]
@ashidov-fy Sorry for the delay. We've updated our build scripts, as well as our [Contributing](https://github.com/rive-app/rive-ios/blob/main/CONTRIBUTING.md) doc, which should now be up-to-date with how to build this runtime.
