### ISSUE TITLE
Font Fallback

### ISSUE THREAD

**Issue by cerupcat** [rive-app/rive-ios#340]
### Description

I'm trying to use system fonts as a fallback (per https://github.com/rive-app/rive-ios/commit/b0474633b814ddb3a188040eab28bab052870f5b) however, when I try to do what the example does and add:

```.onAppear(perform: {
            RiveFont.fallbackFonts = [
                // You can use a font descriptor that will generate a system font
                RiveFallbackFontDescriptor(design: .default, weight: .regular, width: .standard),
                // ...or an explicit system font
                UIFont.systemFont(ofSize: 12, weight: .heavy),
                // ...or a UIFont by name, or any way of initializing a UIFont
                UIFont(name: "Times New Roman", size: 12)!
            ]
        })
```

I receive the following error:  `Cannot find 'RiveFallbackFontDescriptor' in scope`.

What's the right way to export a Rive with font references and use the native system font for those references?

If there's multiple font references (eg. SemiBold, Regular, Heavy, etc), can we map each one to a native font?

**Comment by dskuza** [comment]
Fallback font support was added in v6.1, so make sure you're on the latest to gain its support. Additionally, you'll have to import the Rive runtime: `import RiveRuntime`. These fonts are used globally across all animations when characters are missing from fonts.

Currently, there is no way to return a `UIFont`/`NSFont` to the factory to decode as font data for referenced fonts; those rely on using `Data`. It's something on my list to look into, though!

**Comment by cerupcat** [comment]
> Fallback font support was added in v6.1, so make sure you're on the latest to gain its support. Additionally, you'll have to import the Rive runtime: `import RiveRuntime`. These fonts are used globally across all animations when characters are missing from fonts.
> 
> 
> 
> Currently, there is no way to return a `UIFont`/`NSFont` to the factory to decode as font data for referenced fonts; those rely on using `Data`. It's something on my list to look into, though!

Thanks for the quick response. I am using v6.1.1 and receiving the errors previously mentioned despite importing RiveRuntime.

Also, would the fallback mean if there's a referenced font that isn't set it would automatically fall back to native or is that not the case?

**Comment by dskuza** [comment]
@cerupcat Interesting… I just built a new project from scratch using v6.1.1, and can access the descriptor. Maybe this is a case of cleaning the build folder, quitting Xcode, and deleting derived data? Xcode might be in a funky state.

With regards to fallback fonts, it's when a font is available (embedded or referenced) but contains missing glyphs / characters for the text it's trying to draw. For example, a font that supports only English languages (i.e standard English characters), but contains a text run that is updated at runtime to include non-English text (e.g Japanese Kanji). In this case, fallback fonts can be registered to look for that may contain those missing characters. For these, system fonts can be used. By default, it'll use the default system font, if any are missing. So, not quite what you're looking for, but…

With regards to using system fonts as referenced fonts, I'm looking into it. Currently, there's a factory method (`decodeFont`) that requires `NSData`), but I'm trying to expand that to a second function that can utilize native Apple types.

**Comment by dskuza** [comment]
@cerupcat We just release v6.1.2, which adds a new factory method when decoding fonts: `decodeUIFont:`, or `decodeNSFont:` on macOS (both are `decodeFont(_:)` in Swift). Using the same pattern as decoding fonts for referenced fonts, you can now use a native Apple font as a referenced font. The one quirk is that regardless of what weight / width you provide, the font data will be used to render the text as defined by a text run (e.g if you provide a thin font, but the text in Rive is bold, the font will appear bold)

**Comment by cerupcat** [comment]
> @cerupcat We just release v6.1.2, which adds a new factory method when decoding fonts: `decodeUIFont:`, or `decodeNSFont:` on macOS (both are `decodeFont(_:)` in Swift). Using the same pattern as decoding fonts for referenced fonts, you can now use a native Apple font as a referenced font. The one quirk is that regardless of what weight / width you provide, the font data will be used to render the text as defined by a text run (e.g if you provide a thin font, but the text in Rive is bold, the font will appear bold). I'll be adding some info about this to our docs shortly.

Amazing. I'll give this a try today and make sure the derivedData folder is cleared. Thanks for the quick turnaround on this.

**Comment by dskuza** [comment]
Do reach out if you have any more issues, otherwise feel free to close this issue if you've confirmed things are working on your end!

**Comment by cerupcat** [comment]
> Do reach out if you have any more issues, otherwise feel free to close this issue if you've confirmed things are working on your end!

I'm still debugging, but I can't access the new functions and it seems potentially due to `TARGET_OS_IPHONE` not being defined in our project. Also wondering if that should be `TARGET_OS_IOS` instead.

**Comment by dskuza** [comment]
Are you using Swift or Objective-C? In Swift, you'll be using it similar to the existing decode function (`factory.decodeFont(UIFont.systemFont(...))`. I'd expect that function to be available since the package is pre-built for iOS (I think `TARGET_OS_IPHONE` is available for both iPhone and iPad).

**Comment by cerupcat** [comment]
Ah ok, I misunderstood/misread that part of the code. We're using swift and
we do have access to the `decodeFont`. I'll give that a try and if all
works, I'll mark this as closed. Thanks again!
ᐧ

**Comment by cerupcat** [comment]
Everything is working as expected. Closing this issue. Thanks!
