### ISSUE TITLE
Does v6.3.0 require Xcode 16.0 (which includes Swift 6.0 compiler)?

### ISSUE THREAD

**Issue by graemesi** [rive-app/rive-ios#346]
I previously was using runtime 6.2.1 and Xcode 15.4. I recently updated to 6.3.0 and the runtime no longer compiles:

`Failed to build module 'RiveRuntime'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.`

If I then compile with Xcode 16.0 which contains the Swift 6.0 compiler, it builds correctly. Does this mean we now need to use Xcode 16.0 - and by implication the iOS 18 SDK - to use the latest Rive 6.3.0 runtime for iOS?

**Comment by dskuza** [comment]
@graemesi Thanks for reaching out. I'm working on a fix, and hope to have an updated release today. I'll reach out to let you know when it's available.

**Comment by dskuza** [comment]
@graemesi v6.3.1 should resolve your issue. If it does, please let me know!

**Comment by graemesi** [comment]
@dskuza v6.3.1 fixes the issue for me. Thanks for your help!
