### ISSUE TITLE
Rive animation fails to response after download task

### ISSUE THREAD

**Issue by Noraaa1** [rive-app/rive-ios#351]
**Description:**
I encountered an issue in SwiftUI where I called the reset and play methods of a RiveViewModel within an onTapGesture handler. These methods (reset and play) are executed on the main thread, while a download task starts in a background thread.

After this sequence of actions, the Rive animation fails to reset and play again. It seems that the animation becomes unresponsive.

**Steps to Reproduce:**

Create a SwiftUI view with a RiveViewModel.
In the onTapGesture of an element:
Call the reset and play methods of the Rive animation on the main thread.
Start a download task on a background thread.
Try resetting or replaying the animation again.

**Expected Behavior:**
The Rive animation should reset and play as expected.

**Actual Behavior:**
The animation becomes unresponsive and fails to reset or play again.

**Environment:**

SwiftUI
Rive SDK version: 6.3.3
iOS version: 16.6
Device: iPhone 12

**Comment by dskuza** [comment]
For clarification are you using a `Task` in `onTapGesture`, `DispatchQueue`, or letting something like `URLSession` handle the background threading for you? I just want to make sure I'm understanding.

Additionally, have you tried the latest version of the runtime? Can you provide a sample view that showcases this behavior and share its code here?

**Comment by Noraaa1** [comment]
> For clarification are you using a `Task` in `onTapGesture`, `DispatchQueue`, or letting something like `URLSession` handle the background threading for you? I just want to make sure I'm understanding.
> 
> Additionally, have you tried the latest version of the runtime? Can you provide a sample view that showcases this behavior and share its code here?

I tried the latest version of the runtime and found that the issue has been fixed. Thank you very much!
