### ISSUE TITLE
Not able to run the app

### ISSUE THREAD

**Issue by christybeena** [rive-app/rive-ios#9]
I have cloned the rive-ios app and tried to run it in the simulator but it is showing the following errors. Please guide me through this. I am using Xcode Version 12.1  and MacOS 10.15.7?
![image](https://user-images.githubusercontent.com/34153169/102105137-0a3f6080-3e55-11eb-95d3-df0bf96520f7.png)

**Comment by lenniezelk** [comment]
In the root of the cloned repo run `git submodule update --init` then will work

**Comment by mjohnsullivan** [comment]
Ah yes, you need to pull down the submodule. apologies; that should be made clearer in the README. I'm going to update that now. Thanks for pointing that out.
